# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='N/A', max_length=20000),
            preserve_default=False,
        ),
    ]
